server:
  port: 8002
spring:
  application:
    name: xc-customer-consumer
eureka:
  instance:
    instance-id: xc-customer-consumer
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://60.205.207.9:6001/eureka/
feign:
  hystrix:
    enabled: true

---
spring:
  zipkin:
    base-url: http://60.205.207.9:7777
  sleuth:
    sampler:
       percentage: 1.0
logging:
    level: info